### ISSUE TITLE
Check downloaded filings and parsed items

### ISSUE THREAD

**Issue by hahoangnhan** [nlpaueb/edgar-crawler#12]
Hi,
Thanks for sharing a great package. 
It's not a real issue, but I hope you can update to check if a filing has been downloaded and an item has been parsed in the next version. And by that, we need to download missing filings and parse missing items as needed. 

Sometimes the computer could get crashed and let me restart my session. I saw some filings and items in the output folders, but restarting the session requires Python to start from the beginning. Checking downloaded filings is also helpful in case we want to update the data. 

Best regards,
hhn

**Comment by codinguncut** [comment]
Also see https://github.com/nlpaueb/edgar-crawler/issues/19

**Comment by eloukas** [comment]
Hi @hahoangnhan  @codinguncut.

The code supports "reading from the filings_metadata file". Probably, the issue you are describing is relevant to #19. In other words, in some rare unlucky cases, the filings_metadata would be a file with 0 bytes, because the user, for example, pressed ctrl+c when the code was saving the file. 

Now, this got patched in PR #23, since we make sure we write to a temp file first, move the data to a final one when sure, and if someone presses ctrl+c when saving, the program handles it and make sure the writing operation does not get destroyed in the middle (it waits until it finishes and then exits).
