### ISSUE TITLE
Hi Eloukas, i got a error when using the crawler.py

### ISSUE THREAD

**Issue by liyifu0302** [nlpaueb/edgar-crawler#2]
When i run the crawler.py code in VScode, it returns an error message, it seems like an OS problem. Could you please help me to tackle with it? Many thanks in advance.

OSError: [Errno 22] Invalid argument: 'C:\\Users\\liyif\\Documents\\GitHub\\edgar-crawler\\datasets\\RAW_FILINGS\\1000209_10K_2019_https://www.htm'

**Comment by liyifu0302** [comment]
oh, i manage to solve it, I replace the keyword "://" with "_", it seems the problem comes from the designated path.

**Comment by eloukas** [comment]
Hi Liyifu, 
I am not sure if the problem appeared because of a bug or if you configured something wrong.

Could you please tell me more about the issue so I can replicate it, in case there's a bug in the code repo?

- In which line did the error occur?
- Which argument did you change?
- How exactly did you resolve this?

**Comment by liyifu0302** [comment]
> Hi Liyifu, I am not sure if the problem appeared because of a bug or if you configured something wrong.
> 
> Could you please tell me more about the issue so I can replicate it, in case there's a bug in the code repo?
> 
> * In which line did the error occur?
> * Which argument did you change?
> * How exactly did you resolve this?

Hi Eloukas,

Thanks for your prompt reply.Actually, I guess the problem lies in the line 494 and 547 in edgar_crawler.py

The problem is the file name:
C:\Users\liyif\Documents\GitHub\edgar-crawler\datasets\RAW_FILINGS\1000209_10K_2019_https://www.htm

the system can not recognize "://" in the filename. I solve it by replacing this part with "_" or any other system accepted keywords :).

**Comment by eloukas** [comment]
Did you rename the original file? Instead of the `https`, there should have been the accession number; not any URL link

**Comment by liyifu0302** [comment]
> 

No, I didn't change anything. Just use the VScode to open it, then Run.

**Comment by eloukas** [comment]
Hi Liyi, the filename on both lines should not contain any HTTP link. 

I debugged the code thoroughly and as said, it has the accession number there, not the HTTP link. Everything works correct.

Was it maybe anything about the "C:/" prefix on Windows? 
I am asking because we developed and tested the toolkit on Unix systems.

However, even in that scenario, the `os.path `module of Python is OS-agnostic.
[Source here](https://docs.python.org/3/library/os.path.html)

I am closing this thread and feel free to reopen it in case anything persists.

**Comment by dalayyy** [comment]
> > Hi Liyifu, I am not sure if the problem appeared because of a bug or if you configured something wrong.
> > Could you please tell me more about the issue so I can replicate it, in case there's a bug in the code repo?
> > 
> > * In which line did the error occur?
> > * Which argument did you change?
> > * How exactly did you resolve this?
> 
> Hi Eloukas,
> 
> Thanks for your prompt reply.Actually, I guess the problem lies in the line 494 and 547 in edgar_crawler.py
> 
> The problem is the file name: C:\Users\liyif\Documents\GitHub\edgar-crawler\datasets\RAW_FILINGS\1000209_10K_2019_https://www.htm
> 
> the system can not recognize "://" in the filename. I solve it by replacing this part with "_" or any other system accepted keywords :).

Hi, Liyi!

I am new in the Python. Please can you explain me in which specific line  the "://" should be replaced with "_" in edgar_crawler.py? thank you in advance.

**Comment by nyssarex** [comment]
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Amir\\PycharmProjects\\edgar-crawler\\datasets\\RAW_FILINGS\\1020214_10K_1999_https://www.txt'
 Hi guys, I am also using Windows + Pycharm and this error appearing

**Comment by nyssarex** [comment]
I solved this error by this line guys 
accession_num = accession_num.replace("://", "_")
