### ISSUE TITLE
Great work! Any plan to download an entire set of 10Q textual data onto Huggingface (just like what you did on 10K)?

### ISSUE THREAD

**Issue by hohoCode** [nlpaueb/edgar-crawler#26]
Great work! Any plan to download an entire set of 10Q textual data onto Huggingface (just like what you did on 10K)?

If so, that would be great! Thanks!

**Comment by eloukas** [comment]
Hi @hohoCode. To be honest, no.
The 10-K collection was actually collected (and that's why the OSS started) in order to be able to create some NLP embeddings and unlabeled datasets to be used in some other models at that time.

May I ask what is your end goal (if you had a big 10Q corpus)? 
(In case you have a research direction in goal, I could maybe offer some advice. I have some ideas that I can not chase myself right now.)

**Comment by eloukas** [comment]
Ah, yeah. While this is not exactly what I had in mind, sure, I could chat with you. Feel free to message me on LinkedIn. I'm closing this issue for now!
