### ISSUE TITLE
Extra Forms Parsing

### ISSUE THREAD

**Issue by gpolydatas** [nlpaueb/edgar-crawler#28]
Hi , I have written some code to be able to parse some extra forms ( 3", "4", "SC 13D/A", "SC13G") and I am trying to push to the feature branch but i get access denied. Can someone help me or contact me ?

**Comment by eloukas** [comment]
Hi @gpolydatas, make sure you push it to a feature branch in your own fork of the repo. 

Then, you can proceed and create a pull request in this repo. 

In order to help us review your work, make sure you:
- attach some screenshots of the output
- walk us through your methodology / code revisions and any problems or limitations you found.

thank you for the interest btw!

**Comment by eloukas** [comment]
Hi @gpolydatas, do you want any help on that maybe? Can you maybe add and message me on LinkedIn?

**Comment by gpolydatas** [comment]
Hi Lefteris,

yes , I will defo do so and catch you also on Linkedikn . I'm aiming to do
so after 5 GMT though as its my working hours now:-).

Thanks,
George

**Comment by gpolydatas** [comment]
![image](https://github.com/user-attachments/assets/e3c4f438-ed23-418c-8496-2160207f95a8)
not sure whats happening even after fllowing the exact same guidance from atlassian.

**Comment by eloukas** [comment]
@gpolydatas 

The current repo is protected from "direct outside" write access so things do not get messed up. This is the case with most open-source repositories.

If you want to contribute to this repository, here’s how you can do it:  

1. **Fork the Repository**  
   Go to the original repository's page on GitHub (this one) and click the **Fork** button in the top-right corner. This will create a copy of the repository in your own GitHub account, where you have full write access. Your forked repository will likely be under `https://github.com/gpolydatas/edgar-crawler`.  

2. **Check Your Current Git Remote Settings**  
   Since probably you’ve already cloned the _original_ repository locally and made changes, your _local_ repository is still pointing to _this original_ repository as the "origin."  
   - You can confirm this by running `git remote -v`. It will show that the `origin` remote points to this repository, where you do not have direct write access.  (If everyone had direct write access, it would be super easy for someone to destroy the repo!)

3. **Update Your Git Remote to Point to _Your Fork_**  
   To push your changes, you need to update the `origin` _remote to point to your forked version_ instead. Probably, this command will be enough: `git remote set-url origin https://github.com/gpolydatas/edgar-crawler.git`
After doing this, verify the change using `git remote -v`. Now `origin` should _point to your forked repository_.

4. Push Your Changes to Your Fork
Now that your local repository is connected to your fork, you can push your local changes with `git push`

5. Once your changes are pushed to your fork, go to your forked repository on GitHub. You should see a banner saying something like "You recently pushed branches…" with an option to create a pull request.

- Click `Compare & pull request`.
- Add a description explaining what changes you made and why (attach some screenshots of the output
walk us through your methodology / code revisions and any problems or limitations you found.)
- Submit the pull request.

Once the pull request is submitted, I’ll review it, and if everything looks good, we can merge it into the main repository (this one). Message me directly on LinkedIn if you need more assistance.

**Comment by eloukas** [comment]
Closing this since this is resolved. We can discuss the more technical PR things on the corresponding PR.
