### ISSUE TITLE
UnpicklingError: could not find MARK

### ISSUE THREAD

**Issue by dalayyy** [nlpaueb/edgar-crawler#7]
Hi!
I am trying to load emdeddings in (https://zenodo.org/record/5524358#.Yk9U2ShBxPY), but got the next errorr:
UnpicklingError: could not find MARK
and with this warning - return _pickle.load(f, encoding='latin1')  # needed because loading from S3 doesn't support readline()

Tried this code: model = Word2Vec.load('edgar.word.w2v.200.bin')

**Comment by eloukas** [comment]
Hi there!

You should use the [_gensim.models.Word2Vec.load_word2vec_format_](https://tedboy.github.io/nlps/generated/generated/gensim.models.Word2Vec.load_word2vec_format.html) and put the _binary_ flag to true since the embeddings are given in a binary format.

Tested it in gensim 3.8.3 version btw.
